name: tugas_slicing_starbhak_mart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/monkey1.jpeg
    - assets/monkey2.jpeg
    - assets/monkey3.jpeg
    - assets/makanan.png
    - assets/minuman.png
